version: '2'
services:
  postgresql:
    image: rhpam-postgresql
    volumes:
      - postgresql:/var/lib/pgsql
      - /etc/localtime:/etc/localtime
    expose:
      - "5432"
    environment:
      - POSTGRESQL_USER=jboss
      - POSTGRESQL_PASSWORD=jboss
      - POSTGRESQL_DATABASE=rhpamkieserver
      - POSTGRESQL_EXTENSION=
      - POSTGRESQL_MAX_PREPARED_TRANSACTIONS=100
  rhpam-bc:
    image: rhpam
    mem_limit: 3gb
    expose:
      - "8080"
    environment:
      - KIE_SERVER=false
      - BUSINESS_CENTRAL=true
      - BUSINESS_CENTRAL_DESIGN=true
      - KIE_SERVER_CONTROLLER=false
      - MAVEN_MIRROR_URL=http://nexus:8080/nexus/content/groups/public
      - NEXUS_HOST=nexus
      - GC_MAX_METASPACE_SIZE=500
      - JAVA_MAX_MEM_RATIO=80
      - JAVA_INITIAL_MEM_RATIO=0
      - CLEAN=true
    volumes:
      - /etc/localtime:/etc/localtime
      - rhpam-bc:/opt/jboss/data
  rhpam-kieserver:
    image: rhpam
    mem_limit: 2gb
    expose:
      - "8080"
    environment:
      - PGSQL_RHPAM_SCHEMA=rhpamkieserver
      - QUARTZ=true
      - KIE_SERVER=true
      - BUSINESS_CENTRAL=false
      - RHPAM_EXT_DISABLED=false
      - RHDM_EXT_DISABLED=false
      - BRP_EXT_DISABLED=false
      - JBPMUI_EXT_DISABLED=false
      - RHPAM_CASE_EXT_DISABLED=false
      - KIE_SERVER_BYPASS_AUTH_USER=false
      - KIE_SERVER_ID=1
      - KIE_SERVER_MANAGED=true
      - KIE_SERVER_CONTROLLER_HOST=rhpam-admin
      - KIE_SERVER_CONTROLLER_TYPE=controller
      - EXECUTOR=true
      - EXECUTOR_JMS=true
      - EXECUTOR_POOL_SIZE=1
      - EXECUTOR_RETRY_INTERVAL=3
      - MAVEN_MIRROR_URL=http://nexus:8080/nexus/content/groups/public
      - NEXUS_HOST=nexus
      - JAVA_MAX_MEM_RATIO=80
      - JAVA_INITIAL_MEM_RATIO=0
      - CLEAN=true
      - DEBUG=true
    volumes:
      - /etc/localtime:/etc/localtime
      - rhpam-kieserver:/opt/jboss/data
  rhpam-admin:
    image: rhpam
    mem_limit: 3gb
    expose:
      - "8080"
    environment:
      - BUSINESS_CENTRAL=false
      - BUSINESS_CENTRAL_DESIGN=false
      - KIE_SERVER_CONTROLLER=true
      - KIE_SERVER=false
      - MAVEN_MIRROR_URL=http://nexus:8080/nexus/content/groups/public
      - NEXUS_HOST=nexus
      - GC_MAX_METASPACE_SIZE=500
      - JAVA_MAX_MEM_RATIO=80
      - JAVA_INITIAL_MEM_RATIO=0
      - CLEAN=true
    volumes:
      - /etc/localtime:/etc/localtime
      - rhpam-admin:/opt/jboss/data
volumes:
  postgresql:
  rhpam-bc:
  rhpam-admin:
  rhpam-kieserver:
networks:
  default:
    external:
      name: dockernet
