version: '2'
services:
  eap:
    image: eap7
    expose:
      - "8080"
      - "9990"
      - "9999"
    volumes:
      - /etc/localtime:/etc/localtime
      - eap:/opt/jboss/data
    network_mode: "bridge"   
volumes:
  eap:
