version: '2'
services:
  nexus:
    image: nexus3
    expose:
      - "8080"
    environment:
      - TLS_CRT=nexus3.p12
      - TLS_CRT_NAME=Nexus3-Certificate
      - TLS_CRT_PASSWORD=nexus3.password
    volumes:
      - /etc/localtime:/etc/localtime
      - nexus-data:/data
      - nexus-secret:/opt/secrets
    network_mode: "bridge"
volumes:
  nexus-data:
  nexus-secret: