version: '2'
services:
  postgresql:
    image: postgresql
    expose:
      - "5432"
    volumes:
      - /etc/localtime:/etc/localtime
      - postgresql:/var/lib/pgsql/data
    environment:
      - POSTGRESQL_MAX_CONNECTIONS=100
      - POSTGRESQL_MAX_PREPARED_TRANSACTIONS=0
      - POSTGRESQL_SHARED_BUFFERS=32MB
      - POSTGRESQL_EFFECTIVE_CACHE_SIZE=128MB
      - ENABLE_REPLICATION=false
    network_mode: "bridge"
volumes:
  postgresql: