IP_ADDR=127.0.0.1
RESOURCES_DIR=/resources
CONFIGURATION_DIR=/configuration
EAP_DISTRO=jboss-eap-6.4.4-full-build.zip
EAP=$RESOURCES_DIR/$EAP_DISTRO
BPMS_DISTRO=jboss-bpmsuite-6.2.0.GA-redhat-1-deployable-eap6.x.zip
BPMS=$RESOURCES_DIR/$BPMS_DISTRO
SERVER_INSTALL_DIR=/opt/jboss
SERVER_NAME=bpms
SERVER_NAME_ORIG=jboss-eap-6.4
BPMS_DATA_DIR=$SERVER_INSTALL_DIR/data
REPO_DIR=bpms-repo
MAVEN_DIR=m2
MAVEN_REPO_DIR=$BPMS_DATA_DIR/$MAVEN_DIR/repository
MAVEN_SETTINGS_XML=$CONFIGURATION_DIR/maven/settings.xml
MYSQL_DRIVER_JAR=mysql-connector-java.jar
MYSQL_DRIVER_JAR_DIR=/usr/share/java
MYSQL_MODULE_NAME=com.mysql
CLI_BPMS=$CONFIGURATION_DIR/jboss-as/bpms.cli
JBOSS_CONFIG=standalone.xml
MYSQL_BPMS_SCHEMA=${MYSQL_BPMS_SCHEMA:-bpms}
JAVA_HOME=/usr/lib/jvm/java

# Defaults
DASHBOARD=${DASHBOARD:-false}
QUARTZ=${QUARTZ:-true}
NEXUS=${NEXUS:-true}
KIE_SERVER=${KIE_SERVER:-true}
BUSINESS_CENTRAL=${BUSINESS_CENTRAL:-true}

# Kie-server
BPMS_EXT_DISABLED=${BPMS_EXT_DISABLED:-false}
BRMS_EXT_DISABLED=${BRMS_EXT_DISABLED:-false}
KIE_SERVER_BYPASS_AUTH_USER=${KIE_SERVER_BYPASS_AUTH_USER:-true}
KIE_SERVER_ID=${KIE_SERVER_ID:-1}

# Quartz
QUARTZ_PROPERTIES=$CONFIGURATION_DIR/quartz.properties
CLI_BPMS_QUARTZ=$CONFIGURATION_DIR/jboss-as/bpms-quartz.cli
