version: '2'
services:
  mysql:
    build: mysql
    expose:
      - "3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - mysql:/var/lib/mysql/data
    environment:
      - MYSQL_LOWER_CASE_TABLE_NAMES=1
      - MYSQL_ROOT_PASSWORD=redhat
    network_mode: "bridge"
  rhsso:
    build: rhsso
    links:
      - mysql:mysql
    expose:
      - "8080"
    environment:
      - MYSQL_RHSSO_SCHEMA=keycloak
    volumes:
      - /etc/localtime:/etc/localtime
      - rhsso:/opt/jboss/data
      - rhsso-import:/opt/jboss/import
    network_mode: "bridge"
volumes:
  mysql:
  rhsso:
  rhsso-import:
