version: '2'
services:
  mysql:
    build: mysql
    expose:
      - "3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - mysql:/var/lib/mysql/data
    environment:
      - MYSQL_LOWER_CASE_TABLE_NAMES=1
      - MYSQL_ROOT_PASSWORD=redhat
    network_mode: "bridge"
  keycloak:
    build: keycloak
    links:
      - mysql:mysql
    expose:
      - "8080"
    environment:
      - MYSQL_RHSSO_SCHEMA=keycloak
    volumes:
      - /etc/localtime:/etc/localtime
      - keycloak:/opt/jboss/data
    network_mode: "bridge"
volumes:
  mysql:
  keycloak:
