:numbered!:

== RTGov Server image

Docker image that provides a container for the RTGov Server of the Angrytweet demo application. Built upon the `btison/rtgov` image. 

The image uses FSW 6.0.0.GA

Prerequisites:

* Angrytweet EPN war (angrytweet-epn-situation.war) in `resources` directory.

To build:

----
# cd fsw-rtgov/rtgov
# docker build -t angrytweet/rtgov .
----

To run:

First start the MySQL container:

----
# docker run -d --name=angrytweet-mysql angrytweet/mysql
----

Run the RTGov container and link to the MySQL container:

----
# docker run -d --name=angrytweet-rtgov --link=angrytweet-mysql:mysql angrytweet/rtgov 
----

To get a prompt into the container:

----
# RTGOV_PID_PID=$(docker inspect --format '{{ .State.Pid }}' angrytweet-rtgov)
# nsenter -m -u -n -i -p -t $RTGOV_PID
----


=== Container details:

* RTGov is installed in directory `opt/jboss/rtgov`.

* The RTGov installation includes following components: RTGov server (no DTGov, Switchyard)

* The RTGov instance runs as system user `jboss`.

* The RTGov instance is bound to the IP address of the container.

* RTGov is configured with management user `admin:admin123!`.

* To stop RTGov, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./stop-rtgov.sh
----

* To start FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./start-rtgov.sh
----

* To start RTGov in admin-only mode:
+
----
# ./start-rtgov.sh --admin-only
----
