mysql:
  build: mysql
  expose:
    - "3306"
  volumes:
    - /etc/localtime:/etc/localtime
    - /var/lib/mysql/data
  environment:
    - MYSQL_LOWER_CASE_TABLE_NAMES=1
keycloak:
  build: keycloak
  links:
    - mysql:mysql
  expose:
    - "8080"
  environment:
    - MYSQL_RHSSO_SCHEMA=keycloak
  volumes:
    - /etc/localtime:/etc/localtime
    - /opt/jboss/data