mysql:
  build: mysql
  expose:
    - "3306"
  volumes:
    - /etc/localtime:/etc/localtime
rtgov:
  build: rtgov
  links:
    - mysql:mysql
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/docker-data/fsw:/data

fsw:
  build: fsw
  links:
    - mysql:mysql
    - rtgov:rtgov
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/docker-data/fsw:/data
