:numbered!:

== FSW image

Docker image that provides a container for JBoss Fuse Service Works. Built upon the `btison/fsw-rtgov` image. Uses a MySQL instance running in its own Docker container as database. Enabled for RTGov data collection. The RTGov server runs in its own container.

The image uses FSW 6.0.0.GA

Prerequisites:

* AngryTweet ear archive (switchyard-angrytweet.ear) in `resources` directory
* AngryTweet CRM Service war (crm-service.war) in `resources` directory
* AngryTweet RTGov IP war (angrytweet-ip.war) in `resources` directory
* AngryTweet CRM configuration file (crm.properties) in`resources` directory
* Camel Twitter component jar (camel-twitter-2.10.0.redhat-60024-1.jar) in `resources/modules/camel-twitter` directory
* Twitter4J jars (twitter4j-core-3.0.5.jar, twitter4j-stream-3.0.5.jar) in `resources/modules/twitter4j` directory

To build:

----
# cd angrytweet/fsw
# docker build -t angrytweet/fsw .
----

To run:

First start the MySQL container:

----
# docker run -d --name=angrytweet-mysql angrytweet/mysql
----

Start the RTGov container:

----
# docker run -d --name=angrytweet-rtgov --link=angrytweet-mysql:mysql angrytweet/rtgov 
----

Run the FSW container, link to the MySQL and RTGov containers, and set the environment variables for the AngryTweet application:

----
# docker run -d --name=angrytweet-fsw --link=angrytweet-mysql:mysql --link=angrytweet-rtgov:rtgov -e "ANGRYTWEET_CONSUMERKEY=" -e "ANGRYTWEET_CONSUMERSECRET=" -e "ANGRYTWEET_ACCESSTOKEN=" -e "ANGRYTWEET_SINCEID=" -e "ANGRYTWEET_EMAIL_USERNAME=" -e "ANGRYTWEET_EMAIL_PASSWORD=" -e "ANGRYTWEET_EMAIL_HOST=" btison/angrytweet/fsw 
----

To get a prompt into the container:

----
# FSW_PID=$(docker inspect --format '{{ .State.Pid }}' fsw-rtgov)
# nsenter -m -u -n -i -p -t $FSW_PID
----

=== Container details:

* FSW is installed in directory `opt/jboss/fsw`.

* The FSW installation includes following components: Switchyard, RTGov client (no DTGov, RTGov server)

* The FSW instance runs as system user `jboss`.

* The FSW instance is bound to the IP address of the container.

* FSW is configured with management user `admin:admin123!`.

* To stop FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./stop-fsw.sh
----

* To start FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./start-fsw.sh
----

* To start FSW in admin-only mode:
+
----
# ./start-fsw.sh --admin-only
----
