:numbered!:

== FSW image

Docker image that provides a container for JBoss Fuse Service Works. Built upon the `btison/fsw` image. Uses a MySQL instance running in its own Docker container as database. Enabled for RTGov data collection. The RTGov server runs in its own container.

The image uses FSW 6.0.0.GA

To build:

----
# cd rtgov/fsw
# docker build -t btison/fsw-rtgov .
----

To run:

First start the MySQL container:

----
# docker run -d --name=mysql-fsw-rtgov btison/mysql-fsw-rtgov
----

Start the RTGov container:

----
# docker run -d --name=rtgov --link=mysql-fsw-rtgov:mysql btison/rtgov
----

Run the FSW container and link to the MySQL and RTGov containers:

----
# docker run -d --name=fsw-rtgov --link=mysql-fsw-rtgov:mysql --link=rtgov:rtgov btison/fsw-rtgov 
----

To get a prompt into the container:

----
# FSW_PID=$(docker inspect --format '{{ .State.Pid }}' fsw-rtgov)
# nsenter -m -u -n -i -p -t $FSW_PID
----

=== Container details:

* FSW is installed in directory `opt/jboss/fsw`.

* The FSW installation includes following components: Switchyard, RTGov client (no DTGov, RTGov server)

* The FSW instance runs as system user `jboss`.

* The FSW instance is bound to the IP address of the container.

* FSW is configured with management user `admin:admin123!`.

* To stop FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./stop-fsw.sh
----

* To start FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./start-fsw.sh
----

* To start FSW in admin-only mode:
+
----
# ./start-fsw.sh --admin-only
----
