version: '2'
services:
  openldap:
    image: openldap
    expose:
      - "389"
      - "636"
    volumes:
      - /etc/localtime:/etc/localtime
      - openldap-data:/var/lib/ldap
      - openldap-config:/etc/openldap/slapd.d
      - openldap-certs:/etc/openldap/certs
      - openldap-secrets:/opt/secrets
      - openldap-import:/opt/openldap/import
    environment:
      - LDAP_ORGANISATION=ACME Inc.
      - LDAP_DOMAIN=acme
      - LDAP_BASE_DN=dc=acme,dc=org
      - LDAP_BIND_CN=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin

      - LDAP_LOG_LEVEL=stats

      # Tls
      - LDAP_TLS=true
      - LDAP_TLS_PASSWORD_FILENAME=password
      - LDAP_TLS_CRT_FILENAME=openldap.p12
      - LDAP_TLS_CA_CRT_FILENAME=acme.crt
      - LDAP_TLS_CRT_NAME=LDAP-Certificate
      - LDAP_TLS_ENFORCE=true
    network_mode: "bridge"
volumes:
  openldap-data:
  openldap-config:
  openldap-certs:
  openldap-secrets:
  openldap-import: