version: '2'
services:
  postgresql-gitlab:
    build: postgresql-gitlab
    volumes:
      - postgresql:/var/lib/pgsql
      - /etc/localtime:/etc/localtime
    expose:
      - "5432"
    environment:
      - DB_NAME=gitlab_production
      - DB_USER=gitlab
      - DB_PASS=gitlab
      - DB_EXTENSION=pg_trgm
    network_mode: "bridge"
  redis-gitlab:
    build: redis-gitlab
    network_mode: "bridge"
  gitlab:
    build: gitlab
    links:
      - redis-gitlab:redis
      - postgresql-gitlab:postgresql
    expose:
      - "80"
      - "22"  
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - gitlab:/home/git/data
    environment:
      - GITLAB_HTTPS=false

      - GITLAB_HOST=localhost
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=

      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=gitlab
      - DB_NAME=gitlab_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Europe/Brussels
      - GITLAB_TIMEZONE=Brussels

      - GITLAB_BACKUP_SCHEDULE=disable
      - GITLAB_BACKUP_TIME=01:00

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_GRAVATAR_ENABLED=false

      - NGINX_MAX_UPLOAD_SIZE=50m

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - OAUTH_ENABLED=false
    network_mode: "bridge"
volumes:
  postgresql:
  gitlab:
