:numbered!:

== BPMS image

Docker image that provides a container for JBoss BPMS configured with a persistent quartz-based timer. Built upon the `btison/bpms` image. Uses a MySQL instance running in its own Docker container as database.

The image uses BPMS 6.0.2.GA.

To build:

----
# cd bpms-quartz/bpms
# docker build -t btison/bpms-quartz .
----

To run:

First start the MySQL container:

----
# docker run -d --name=mysql-bpms btison/mysql-bpms-quartz
----

Run the BPMS container and link to the MySQL container:

----
# docker run -d --name=bpms --link=mysql-bpms-quartz:mysql btison/bpms-quartz 
----

To get a prompt into the container:

----
# BPMS_PID=$(docker inspect --format '{{ .State.Pid }}' bpms)
# nsenter -m -u -n -i -p -t $BPMS_PID
----

Both containers can also be started using fig (http://www.fig.sh):

----
# cd bpms-quartz
# fig up -d
----


=== Container details:

* BPMS is installed in directory `opt/jboss/bpms`.

* The BPMS instance runs as system user `jboss`.

* The BPMS instance is bound to the IP address of the container.

* BPMS is configured with management user `admin:admin`.

* BPMS is configured to use a persistent quartz timer

* BPMS is configured with application users:
** `admin1:admin` with roles `admin,analyst,user,reviewer`
** `user:user` with roles `user,reviewer`

* To stop BPMS, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./stop-bpms.sh
----

* To start BPMS, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./start-bpms.sh
----

* To start BPMS in admin-only mode:
+
----
# ./start-bpms.sh --admin-only
----
