version: '2'
services:
  postgresql:
    image: rhsso-postgresql
    volumes:
      - postgresql:/var/lib/pgsql
      - /etc/localtime:/etc/localtime
    expose:
      - "5432"
    environment:
      - POSTGRESQL_USER=jboss
      - POSTGRESQL_PASSWORD=jboss
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_EXTENSION=
  rhsso:
    image: rhsso
    expose:
      - "8080"
    environment:
      - POSTGRESQL_RHSSO_SCHEMA=keycloak
      - USE_TLS=true
      - TLS_CA_CRT=acme.crt
      - TLS_CRT=rhsso.p12
      - TLS_CRT_NAME=RHSSO-Certificate
      - TLS_CRT_PASSWORD=password
    volumes:
      - /etc/localtime:/etc/localtime
      - rhsso:/opt/jboss/data
      - rhsso-import:/opt/jboss/import
      - rhsso-secret:/opt/secrets
volumes:
  postgresql:
  rhsso:
  rhsso-import:
  rhsso-secret:
networks:
  default:
    external:
      name: dockernet
