:numbered!:

== RTGov Server image

Docker image that provides a container for JBoss Fuse Service Works RTgov Server. Built upon the `btison/java` image. Uses a MySQL instance running in its own Docker container as database.

The image uses FSW 6.0.0.GA

Prerequisites:

* FSW installer (jboss-fsw-installer-6.0.0.GA-redhat-4.jar) in `resources` directory.
* Missing modules in `resources/modules` directory. + 
When installing only RTGov server, some modules are not installed. Copy the following modules from the `$JBOSS_HOME/modules/system/layers/soa` directory of an existing FSW installation
** `com/google/protobuf`
** `com/thoughtworks/xstream`
** `org/antlr/antlr-runtime`
** `org/apache/poi`
** `org/jboss/hibernate/custom-dialect-resolvers/hibernate-dialect-resolvers`
** `org/mvel`
** `org/mvel/mvel2`

To build:

----
# cd fsw-rtgov/rtgov
# docker build -t btison/rtgov .
----

To run:

First start the MySQL container:

----
# docker run -d --name=mysql-fsw-rtgov btison/mysql-fsw-rtgov
----

Run the FSW container and link to the MySQL container:

----
# docker run -d --name=rtgov --link=mysql-fsw-rtgov:mysql btison/rtgov 
----

To get a prompt into the container:

----
# RTGOV_PID_PID=$(docker inspect --format '{{ .State.Pid }}' rtgov)
# nsenter -m -u -n -i -p -t $RTGOV_PID
----


=== Container details:

* RTGov is installed in directory `opt/jboss/rtgov`.

* The RTGov installation includes following components: RTGov server (no DTGov, Switchyard)

* The RTGov instance runs as system user `jboss`.

* The RTGov instance is bound to the IP address of the container.

* RTGov is configured with management user `admin:admin123!`.

* To stop RTGov, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./stop-rtgov.sh
----

* To start FSW, enter the container with _nsenter_ and issue the following command (as root)
+
----
# ./start-rtgov.sh
----

* To start RTGov in admin-only mode:
+
----
# ./start-rtgov.sh --admin-only
----
