mysql:
  build: mysql
  expose:
    - "3306"
  volumes:
    - /etc/localtime:/etc/localtime
    - /var/lib/mysql/data
  environment:
    - MYSQL_LOWER_CASE_TABLE_NAMES=1
nexus:
  build: nexus
  expose:
    - "8080"
  volumes:
    - /etc/localtime:/etc/localtime
    - /data
bpms:
  build: bpms
  links:
    - mysql:mysql
    - nexus:nexus
  expose:
    - "8080"
  environment:
    - MYSQL_BPMS_SCHEMA=bpms
    - DASHBOARD=false
    - QUARTZ=true
    - NEXUS=true
    - KIE_SERVER=false
    - BUSINESS_CENTRAL=true
  volumes:
    - /etc/localtime:/etc/localtime
    - /opt/jboss/data
