version: '2'
services:
  gogs:
    image: gogs
    volumes:
      - gogs:/app/gogs/data
      - /etc/localtime:/etc/localtime
    expose:
      - "3000"
      - "2222"
    environment:
      - ADMIN_USER_CREATE=true
      - ADMIN_USER_NAME=gogsadmin
      - ADMIN_USER_EMAIL=gogsadmin@example.com
      - ADMIN_USER_PASSWORD=admin123
      - GOGS_SECURITY__INSTALL_LOCK=true
      - GOGS_RUN_USER=git
      - GOGS_RUN_MODE=prod
      - GOGS_REPOSITORY__ROOT=/app/gogs/data/repositories
      - GOGS_SERVER__DOMAIN=gogs-gogs-1.gogs.docker
      - GOGS_SERVER__START_SSH_SERVER=true
      - GOGS_SERVER__SSH_PORT=2222
      - GOGS_SERVER__SSH_ROOT_PATH=/app/gogs/data/git/.ssh
      - GOGS_SERVER__APP_DATA_PATH=/app/gogs/data
      - GOGS_DATABASE__DB_TYPE=sqlite3
      - GOGS_DATABASE__PATH=/app/gogs/data/gogs.db
      - GOGS_SERVICE__ENABLE_REVERSE_PROXY_AUTHENTICATION=true
      - GOGS_SERVICE__ENABLE_REVERSE_PROXY_AUTO_REGISTRATION=true
      - GOGS_SESSION__PROVIDER_CONFIG=/app/gogs/data/sessions
      - GOGS_PICTURE__AVATAR_UPLOAD_PATH=/app/gogs/data/avatars
      - GOGS_ATTACHMENT__PATH=/app/gogs/data/attachments
      - GOGS_LOG__ROOT_PATH=/app/gogs/data/logs
      - GOGS_LOG__LEVEL=Error
volumes:
  gogs:
networks:
  default:
    external:
      name: dockernet