version: '2'
services:
  kafka1:
    build: 
      context: kafka
    volumes:
      - /etc/localtime:/etc/localtime
      - kafka1-log:/opt/kafka/kafka-log
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZK_1=zk-zk1-1.zk-zk1.docker:2181
      - KAFKA_ZK_2=zk-zk2-1.zk-zk2.docker:2181
      - KAFKA_ZK_3=zk-zk3-1.zk-zk3.docker:2181
    network_mode: "bridge"
  kafka2:
    build: 
      context: kafka
    volumes:
      - /etc/localtime:/etc/localtime
      - kafka2-log:/opt/kafka/kafka-log
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZK_1=zk-zk1-1.zk-zk1.docker:2181
      - KAFKA_ZK_2=zk-zk2-1.zk-zk2.docker:2181
      - KAFKA_ZK_3=zk-zk3-1.zk-zk3.docker:2181
    network_mode: "bridge"
volumes:
  kafka1-log:
  kafka2-log: