mysql:
  build: mysql
  expose:
    - "3306"
  volumes:
    - /etc/localtime:/etc/localtime
nexus:
  build: nexus
  expose:
    - "8080"
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/docker-data/nexus:/data
bpms:
  build: bpms
  links:
    - mysql:mysql
    - nexus:nexus
  expose:
    - "8080"
    - "9990"
    - "9999"
  volumes:
    - /etc/localtime:/etc/localtime
    - /data/docker-data/bpms:/data
