version: '2'
services:
  jenkins-slave-maven:
    image: jenkins-slave-maven
    volumes:
      - jenkins-ssh:/home/jenkins/.ssh
      - /etc/localtime:/etc/localtime
volumes:
  jenkins-ssh:
networks:
  default:
    external:
      name: dockernet